#!/bin/bash
# BankCore Analytics - Quick Start Script

echo "=================================================="
echo "  BankCore Analytics - Installation Complete!"
echo "=================================================="
echo ""
echo "INSTALLATION STATUS:"
echo "  [OK] Frontend dependencies installed"
echo "  [OK] Backend virtual environment created"
echo "  [OK] Backend packages installed:"
echo "       - FastAPI"
echo "       - Uvicorn"
echo "       - DuckDB"
echo "       - PyArrow"
echo "       - Pydantic"
echo ""
echo "  [OK] Data files verified:"
echo "       - customers.parquet (4.7M, 100K records)"
echo "       - loans.parquet (15M, 500K records)"
echo "       - transactions/ (365 date partitions)"
echo "       - fraud_labels.parquet (482K, 50K records)"
echo ""
echo "=================================================="
echo "  READY TO RUN!"
echo "=================================================="
echo ""
echo "TERMINAL 1 - Start Backend API (Port 8000):"
echo "  cd backend"
echo "  . ./venv/Scripts/activate    (Windows Git Bash/MSYS2)"
echo "  # OR: venv\Scripts\activate  (Windows PowerShell/CMD)"
echo "  # OR: source venv/bin/activate (macOS/Linux)"
echo "  python main.py"
echo ""
echo "TERMINAL 2 - Start Frontend (Port 3000):"
echo "  cd frontend"
echo "  npm run dev"
echo ""
echo "TERMINAL 3 (Optional) - View API Documentation:"
echo "  Open: http://localhost:8000/docs"
echo ""
echo "BROWSER:"
echo "  Open: http://localhost:3000"
echo ""
echo "=================================================="
echo ""
